modLoader="javafml"
loaderVersion="${forge_loader_versions}"
license="${mod_license}"
issueTrackerURL="${issues_url}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
logoFile="${mod_icon}"
features={java_version="${java_versions_neoforge}"}
credits="${mod_contributors_string}"
authors="${mod_authors_string}"
displayURL="${homepage_url}"

[[mixins]]
config="${mod_id}.mixins.json"
[[mixins]]
config="${mod_id}.forge.mixins.json"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_versions_neoforge}" #optional:any

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_versions}"
side="CLIENT"

# https://docs.minecraftforge.net/en/latest/gettingstarted/modfiles/
# https://docs.minecraftforge.net/en/latest/misc/updatechecker/
# https://files.minecraftforge.net/
