blank_issues_enabled: true
contact_links:
  - name: Support enquiry, Question or Discussion
    url: https://discord.gg/sSgQ9AF4mU
    about: For any issue that isn't specifically a bug report or feature request, please use Discord
