buildscript {
    dependencies.add("classpath", "org.spongepowered:vanillagradle:${vanillagradle_version}")
}

plugins {
    id("multiloader-common")
    id("org.spongepowered.gradle.vanilla")
}

dependencies {
    // Mixin and MixinExtras
    compileOnly("org.spongepowered:mixin:${mixin_version}")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixinextras_version}"))

    // CommandKeys
    implementation("maven.modrinth:65UyswbY:${commandkeys_version}")

    // ChatHeads
    implementation("maven.modrinth:Wb5oqrBJ:${chatheads_version}")
}

minecraft {
    version(minecraft_version)
    if (file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWideners(file("src/main/resources/${mod_id}.accesswidener"))
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
