/*
 * Copyright 2023, 2024 NotRyken
 * SPDX-License-Identifier: Apache-2.0
 */

package com.notryken.chatnotify.config;

import com.google.gson.*;
import net.minecraft.sounds.SoundSource;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Compatible with config files generated by ChatNotify versions 1.2.0-pre.3 to
 * 1.2.0 (inclusive).
 */
public class IntermediaryConfigDeserializer implements JsonDeserializer<Config> {
    @Override
    @SuppressWarnings("unchecked")
    public Config deserialize(JsonElement json, Type typeOfT,
                              JsonDeserializationContext ctx) throws JsonParseException {
        JsonObject obj = json.getAsJsonObject();

        TriState mixinEarly = new TriState(obj.get("mixinEarly").getAsBoolean() ? TriState.State.ON : TriState.State.DISABLED);
        TriState debugShowKey = new TriState(obj.get("debugShowKey").getAsBoolean() ? TriState.State.ON : TriState.State.DISABLED);
        boolean checkOwnMessages = obj.get("checkOwnMessages").getAsBoolean();
        SoundSource soundSource = SoundSource.valueOf(obj.get("soundSource").getAsString());
        boolean allowRegex = false;
        int defaultColor = Config.DEFAULT_COLOR;
        Sound defaultSound = Config.DEFAULT_SOUND;
        List<String> prefixes = new ArrayList<>(
                obj.getAsJsonArray("prefixes")
                        .asList().stream().map(JsonElement::getAsString).toList());
        List<Notification> notifications = new ArrayList<>();

        for (JsonElement je : obj.get("notifications").getAsJsonArray()) {
            JsonObject notifObj = je.getAsJsonObject();

            allowRegex = allowRegex || notifObj.get("allowRegex").getAsBoolean();

            boolean enabled = notifObj.get("enabled").getAsBoolean();
            boolean exclusionEnabled = notifObj.get("exclusionEnabled").getAsBoolean();
            boolean responseEnabled = notifObj.get("responseEnabled").getAsBoolean();
            Sound sound = ctx.deserialize(notifObj.get("sound"), Sound.class);
            TextStyle textStyle = ctx.deserialize(notifObj.get("textStyle"), TextStyle.class);
            List<Trigger> triggers = new ArrayList<>((List<Trigger>) (List<?>)
                    notifObj.getAsJsonArray("triggers")
                            .asList().stream().map(je2 -> ctx.deserialize(je2, Trigger.class))
                            .filter(Objects::nonNull).toList());
            List<Trigger> exclusionTriggers = new ArrayList<>((List<Trigger>) (List<?>)
                    notifObj.getAsJsonArray("exclusionTriggers")
                            .asList().stream().map(je2 -> ctx.deserialize(je2, Trigger.class))
                            .filter(Objects::nonNull).toList());
            List<ResponseMessage> responseMessages = new ArrayList<>(
                    notifObj.getAsJsonArray("responseMessages")
                    .asList().stream().map(je2 -> new ResponseMessage(true, je2.getAsString(), false, 0)).toList());

            notifications.add(new Notification(enabled, exclusionEnabled, responseEnabled,
                    sound, textStyle, triggers, exclusionTriggers, responseMessages));
        }

        // Validate username notification
        if (notifications.isEmpty()) {
            notifications.add(Notification.createUser());
        }
        else if (notifications.get(0).triggers.size() < 2) {
            notifications.set(0, Notification.createUser());
        }

        return new Config(mixinEarly, debugShowKey, checkOwnMessages, soundSource,
                allowRegex, defaultColor, defaultSound, prefixes, notifications);
    }
}
