# Synchronizes the repo's labels with labels.yml
name: Sync Labels

on:
  push:
    paths: ['.github/labels.yml', '.github/workflows/sync-labels.yml']
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/labels.yml
          sparse-checkout-cone-mode: false
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npx github-label-sync -a '${{ secrets.GITHUB_TOKEN }}' -l '.github/labels.yml' ${{ github.repository }}
